export const mockIncidents = [
  {
    id: 101,
    title: 'Checkout failures for premium customers',
    customer: 'Northwind Retail',
    priority: 'Critical',
    status: 'Open',
    assignee: 'Marta Silva',
    service: 'Payments',
    slaTarget: '30 min',
    createdAt: '2026-06-24T08:45:00Z',
    description:
      'High-value carts complete authorization, then fail during order confirmation for a subset of premium accounts.',
  },
  {
    id: 102,
    title: 'Warehouse sync delayed after nightly batch',
    customer: 'Contoso Logistics',
    priority: 'High',
    status: 'In Progress',
    assignee: 'Diogo Ramos',
    service: 'Inventory sync',
    slaTarget: '2 hours',
    createdAt: '2026-06-24T09:20:00Z',
    description:
      'Nightly reconciliation finished late and warehouse availability is lagging by more than 40 minutes.',
  },
  {
    id: 103,
    title: 'Password reset delivery degraded',
    customer: 'Fabrikam Health',
    priority: 'Medium',
    status: 'Open',
    assignee: 'Ana Costa',
    service: 'Identity',
    slaTarget: '4 hours',
    createdAt: '2026-06-23T16:10:00Z',
    description:
      'Password reset requests are accepted, but transactional email delivery is delayed for several customer domains.',
  },
  {
    id: 104,
    title: 'Billing export variance closed',
    customer: 'Adventure Works',
    priority: 'Low',
    status: 'Resolved',
    assignee: 'Joao Pereira',
    service: 'Billing',
    slaTarget: 'Next day',
    createdAt: '2026-06-23T11:35:00Z',
    description:
      'Finance validated the corrected monthly export after duplicate tax rows were removed from the report.',
  },
  {
    id: 105,
    title: 'Order history timeout on mobile',
    customer: 'Tailspin Traders',
    priority: 'High',
    status: 'In Progress',
    assignee: 'Beatriz Lima',
    service: 'Mobile API',
    slaTarget: '90 min',
    createdAt: '2026-06-24T10:05:00Z',
    description:
      'Large account profiles time out when mobile users open order history with more than 2,000 records.',
  },
  {
    id: 106,
    title: 'Production import review pending',
    customer: 'Blue Yonder Labs',
    priority: 'Medium',
    status: 'Open',
    assignee: 'Rui Martins',
    service: 'Data import',
    slaTarget: 'Today',
    createdAt: '2026-06-24T10:40:00Z',
    description:
      'Implementation team needs an integration review before the first production data load is approved.',
  },
];
